writeFileFromByteArray(android.util.Base64.decode(" AAEAAAANAIAAAwBQRkZUTV4dbQIAAE08AAAAHEdERUYA/QAEAABNHAAAACBPUy8yZi731QAAAVgAAABgY21hcBnSMe8AAAT4AAABwmdhc3D//wADAABNFAAAAAhnbHlmMIJYzgAACGAAADXkaGVhZAbv/L0AAADcAAAANmhoZWEIAwLRAAABFAAAACRobXR4LIADgAAAAbgAAANAbG9jYV+9UiwAAAa8AAABom1heHAA2wAoAAABOAAAACBuYW1l99attAAAPkQAAAzDcG9zdC5WmZcAAEsIAAACDAABAAAAAQAADPyv718PPPUACwQAAAAAANGoXGAAAAAA0ahcYAAA/4AEgAOAAAAACAACAAAAAAAAAAEAAAOA/4AAAAUAAAD9gASAAAEAAAAAAAAAAAAAAAAAAADQAAEAAADQACgACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgJnAZAABQAEAgACAAAA/8ACAAIAAAACAAAzAMwAAAAABAAAAAAAAACAAAAHAAAACgAAAAAAAAAARlNUUgBAAA0hIgOA/4AAAAOAAIAAAAH7AAAAAAKAA4AAAAAgAAEBAAAAAAAAAAAAAAABAAAAAQAAAAIAAAACgAAAAwAAAAMAAAADAAAAAQAAAAKAAAACgAAAAoAAAAMAAAABAAAAAwAAAAEAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAEAAAABAAAAAoAAAAMAAAACgAAAAoAAAAOAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAIAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAIAAAADAAAAAgAAAAMAAAADAAAAAYAAAAMAAAADAAAAAwAAAAMAAAADAAAAAoAAAAMAAAADAAAAAQAAAAMAAAACgAAAAYAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAACAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAoAAAAEAAAACgAAAA4AAAAEAAAACgAAAAoAAAAIAAAADAAAAAQAAAAMAAAADgAAAAgAAAAMAAAADAAAAAoAAgAOAAAADAAAAAgAAAAMAAAABgAAAAYAAAAMAAYADAAAAAwAAAAEAAAACgACAAQAAAAIAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAOAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAKAAAADAACAAwAAAAIAAAADgAAAA4AAAAMAAAADAAAAAwAAAAOAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADgAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAABgAAAAYAAAAMAAAACgACAA4AAAAMAAAADAAAAAwAAAAOAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAAwAAAAMAAAADAAAAA4AAAAGAAAABgAAAAYAAAAGAAAACgAAAAoAAAAKAAAACAAAAAYAAAAMAAAAAgAAAAYAAAAMAAAAFAAAAAAAAAwAAAAMAAAAcAAEAAAAAALwAAwABAAAAHAAEAKAAAAAkACAABAAEAAAADQB+AKYA3gDvAP8BUwF4IBQgHiAgICIgJiA6IKwhIv//AAAAAAANACAAoQCoAOAA8QFSAXggFCAYICAgIiAmIDkgrCEi//8AAf/1/+P/wf/A/7//vv9s/0jgreCq4KngqOCl4JPgIt+tAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEGAAABAAAAAAAAAAECAAAAAgAAAAAAAAAAAAAAAAAAAAEAAAMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoKSorLC0uLzAxMjM0NTY3ODk6Ozw9Pj9AQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVpbXF1eX2BhAISFh4mRlpygn6GjoqSmqKepqqyrra6vsbCytLO4t7m6yXBjZADKdgBuac90aACGmABxAABmdQAAAAAAanoApbZ/YmwAAAAAa3vLAICDlb6/AMHGx8LDtQC9wADOzM0AAAB3xMgAgoqBi4iNjo+Mk5QAkpqbmQAAAG8AAAB4AAAAAAAAAAAqACoAKgAqADwAUACAAK4A4AEgAS4BUgF2AZoBsgG+AcoB1gH4AigCPgJwAqQCyALuAxYDNANqA5YDqgO+A+wEAAQsBFgEfgSaBMAE5AT+BRQFKAVKBWIFdgWOBbwFygXuBhIGMgZOBnoGnAbIBtoG9AccB0AHegeeB8YH2AgACBIINAhACEwIbAiQCLQI1gj2CRIJNglWCWgJiAmyCcQJ6An+Ch4KRApoCogKqgrGCtwLAAsaC1ILcguSC7gLxAvqDAgMGgw0DFQMdgyqDL4M7A0MDR4NXA1sDXoNng2qDb4N3A3wDgIOEA4kDkQOUA5iDnAOhA7ADvoPLg9mD44Psg/UEAIQNBBcEH4QoBDSEPARDhE6EVwReBGUEbwR3BIAEjISWhKCErQS6hMWE04TeBOYE7gT5BQKFDYUXBSCFKgU2hUQFTwVYhWOFcAV6BYOFkAWbBaAFpIWshbKFvIXGhdCF3QXqhfWF/AYGBg0GFAYeBiYGMAY5hkSGTIZYBmQGZwZrhnAGdIZ5hoEGiIaQBpWGmQaehqQGqYa0BryAAAABQAAAAADgAOAAAMABwALABIAFgAAJTUjFSU1IRU3NSMVJTUjIgcGFQERIREBwI8BHf7jj48BHY48KSr+zwOAf46Opo+Ppo+Pp40pKjr9jgOA/IAAAgAAAAAAgAOAAAMABwAAMTUzFQMRMxGAgICAgAEAAoD9gAAAAgAAAgABgAOAAAMABwAAGQEzETMRMxGAgIACAAGA/oABgP6AAAAAAAIAAAAAAoADgAADAB8AAAE1IxUDESM1MzUjNTMRMxEzETMRMxUjFTMVIxEjESMRAYCAgICAgICAgICAgICAgIABgICA/oABAICAgAEA/wABAP8AgICA/wABAP8AAAAAAAUAAAAAAoADgAAHAAsADwATABsAACE1ITUhFSMVEzUzFSU1IRUlNTMVPQEzNTMVIRUBAP8AAgCAgID+AAGA/gCAgIABAICAgIABAICAgICAgICAgICAgIAAAAAABwAAAAACgAOAAAMABwALAA8AEwAXABsAADE1MxUhETMRJREzGQE1MxU1ETMRJREzESU1MxWAAYCA/gCAgID+AIABgICAgAEA/wCAAQD/AAEAgICAAQD/AIABAP8AgICAAAAAAAgAAAAAAoADgAADAAcACwAPABsAHwAjACcAADM1IRUzNTMVJREzEQE1MxUBNSM1IzUzNTMRMxEBNTMVMzUzFSU1MxWAAQCAgP2AgAGAgP8AgICAgID+gICAgP8AgICAgICAAQD/AAEAgID/AICAgID/AP8AAgCAgICAgICAAAAAAQAAAgAAgAOAAAMAABkBMxGAAgABgP6AAAAAAAUAAAAAAgADgAADAAcACwAPABMAACE1IRUlNTMVJREzGQE1MxU9ASEVAQABAP6AgP8AgIABAICAgICAgAGA/oABgICAgICAAAUAAAAAAgADgAADAAcACwAPABMAADE1IRU9ATMVNREzEQE1MxUlNSEVAQCAgP8AgP6AAQCAgICAgIABgP6AAYCAgICAgAAAAAUAAAEAAgACgAADAAcACwAPABMAABE1MxUhNTMVJTUhFSU1MxUhNTMVgAEAgP6AAQD+gIABAIABAICAgICAgICAgICAgAAAAAEAAACAAoADAAALAAAlESE1IREzESEVIREBAP8AAQCAAQD/AIABAIABAP8AgP8AAAEAAP+AAIABAAADAAAVETMRgIABgP6AAAEAAAGAAoACAAADAAARNSEVAoABgICAAAEAAAAAAIABAAADAAAxETMRgAEA/wAAAAUAAAAAAoADgAADAAcACwAPABMAADE1MxU1ETMZATUzFTURMxkBNTMVgICAgICAgIABAP8AAQCAgIABAP8AAQCAgAAABQAAAAACgAOAAAMABwAPABcAGwAAMzUhFQE1MxUBETMRMxUjFSERIzUzNTMRATUhFYABgP8AgP6AgICAAYCAgID+AAGAgIABgICA/wACgP6AgIABgICA/YACgICAAAAAAQAAAAACgAOAAAsAADE1IREjNTM1MxEhFQEAgICAAQCAAgCAgP0AgAAAAAAGAAAAAAKAA4AABwALAA8AEwAXABsAADERMxUhNTMRATUzFT0BIRUBNTMVBREzEQE1IRWAAYCA/gCAAQD+AIABgID+AAGAAQCAgP8AAQCAgICAgAEAgICAAQD/AAEAgIAAAAAABwAAAAACgAOAAAMABwALAA8AEwAXABsAADM1IRUlNTMVIREzEQE1IRUBNTMVBREzEQE1IRWAAYD+AIABgID+gAEA/gCAAYCA/gABgICAgICAAQD/AAEAgIABAICAgAEA/wABAICAAAADAAAAAAKAA4AAAwAHABMAABM1MxU9ATMVExEhETMVIREjNSERgICAgP4AgAGAgAEAAgCAgICAgP2AAQABAIABgID8gAAAAAAEAAAAAAKAA4AAAwAHAAsAEwAAMzUhFSU1MxUhETMRAREhFSEVIRWAAYD+AIABgID9gAKA/gABgICAgICAAYD+gAGAAYCAgIAAAAAABQAAAAACgAOAAAMABwAPABMAFwAAMzUhFTURMxEhETMVIRUhGQE1MxU9ASEVgAGAgP2AgAGA/oCAAQCAgIABAP8AAgCAgP8AAgCAgICAgAADAAAAAAKAA4AAAwAHAA8AACERMxkBNTMVNREhFSMRIREBAICA/oCAAoABgP6AAYCAgIABAIABAP6AAAAHAAAAAAKAA4AAAwAHAAsADwATABcAGwAAMzUhFSURMxEhETMRATUhFSURMxEhETMRATUhFYABgP4AgAGAgP4AAYD+AIABgID+AAGAgICAAQD/AAEA/wABAICAgAEA/wABAP8AAQCAgAAAAAAFAAAAAAKAA4AAAwAHAAsAEwAXAAAzNSEVPQEzFQERMxEBNSE1IREzEQE1IRWAAQCA/gCAAYD+gAGAgP4AAYCAgICAgAGAAQD/AP8AgIABAP4AAgCAgAAAAgAAAAAAgAKAAAMABwAAMREzEQMRMxGAgIABAP8AAYABAP8AAAAAAAIAAP+AAIACgAADAAcAABURMxEDETMRgICAgAGA/oACAAEA/wAAAAAHAAAAAAIAA4AAAwAHAAsADwATABcAGwAAITUzFSU1MxUlNTMVJTUzFT0BMxU9ATMVPQEzFQGAgP8AgP8AgP8AgICAgICAgICAgICAgICAgICAgICAgICAAAAAAAIAAACAAoACAAADAAcAAD0BIRUBNSEVAoD9gAKAgICAAQCAgAAAAAAHAAAAAAIAA4AAAwAHAAsADwATABcAGwAAMTUzFT0BMxU9ATMVPQEzFSU1MxUlNTMVJTUzFYCAgID/AID/AID/AICAgICAgICAgICAgICAgICAgICAgAAABgAAAAACgAOAAAMABwALAA8AEwAXAAAhNTMVAzUzFT0BMxUBNTMVBREzEQE1IRUBAICAgID+AIABgID+AAGAgIABAICAgICAAQCAgIABAP8AAQCAgAAAAAQAAAAAAwADgAADAAcADwATAAAzNSEVJREzETcRIREzETMRATUhFYACAP2AgIABAICA/YACAICAgAKA/YCAAYD/AAGA/gACAICAAAACAAAAAAKAA4AACwAPAAAxETMVITUzESMRIRkBNSEVgAGAgID+gAGAAwCAgP0AAgD+AAMAgIAAAAMAAAAAAoADgAADAAcAEwAAJREzEQM1MxUBESEVIRUhFSERIRUCAICAgP2AAgD+gAGA/oABgIABgP6AAgCAgP2AA4CAgID+gIAAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAzNSEVPQEzFSERMxEBNTMVJTUhFYABgID9gIABgID+AAGAgICAgIACgP2AAgCAgICAgAACAAAAAAKAA4AAAwALAAAlETMRBREhFSERIRUCAID9gAIA/oABgIACgP2AgAOAgP2AgAAAAQAAAAACgAOAAAsAADERIRUhFSEVIREhFQKA/gABAP8AAgADgICAgP6AgAABAAAAAAKAA4AACQAAMREhFSEVIRUhEQKA/gABAP8AA4CAgID+AAAABAAAAAACgAOAAAMACQANABEAADM1IRU1ESM1IREhETMZATUhFYABgIABAP2AgAIAgICAAYCA/gACgP2AAoCAgAAAAAABAAAAAAKAA4AACwAAMREzESERMxEjESERgAGAgID+gAOA/wABAPyAAgD+AAAAAAABAAAAAAGAA4AACwAAMTUzESM1IRUjETMVgIABgICAgAKAgID9gIAAAwAAAAACgAOAAAMABwALAAAzNSEVJTUzFSERMxGAAYD+AIABgICAgICAgAMA/QAABQAAAAACgAOAAAMABwALABMAFwAAIREzEQE1MxUDNTMVAREzESEVIREBNTMVAgCA/wCAgID+AIABAP8AAYCAAYD+gAGAgIABAICA/YADgP8AgP4AAwCAgAAAAAABAAAAAAKAA4AABQAAMREzESEVgAIAA4D9AIAAAwAAAAACgAOAAAMACwATAAABNTMVAREzFTMVIxEhESM1MzUzEQEAgP6AgICAAYCAgIACAICA/gADgICA/YACgICA/IAAAAAAAwAAAAACgAOAAAMACwATAAABNTMVAREzFTMVIxEhESM1MxEzEQEAgP6AgICAAYCAgIACAICA/gADgICA/YABgIABgPyAAAAABAAAAAACgAOAAAMABwALAA8AADM1IRUlETMRIREzEQE1IRWAAYD+AIABgID+AAGAgICAAoD9gAKA/YACgICAAAIAAAAAAoADgAADAA0AAAE1MxUBESEVIRUhFSERAgCA/YACAP6AAYD+gAKAgID9gAOAgICA/gAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVMzUzFSU1MxUhETMRJREzEQE1IRWAAQCAgP8AgP4AgAGAgP4AAYCAgICAgICAAoD9gIACAP4AAgCAgAAAAAMAAAAAAoADgAADAAcAEQAAIREzEQM1MxUBESEVIRUhFSERAgCAgID9gAIA/oABgP6AAgD+AAKAgID9gAOAgICA/gAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVJTUzFSERMxEBNSEVJTUzFT0BIRWAAYD+AIABgID+AAGA/gCAAgCAgICAgAGA/oABgICAgICAgICAAAAAAAEAAAAAAoADgAAHAAAhESE1IRUhEQEA/wACgP8AAwCAgP0AAAMAAAAAAoADgAADAAcACwAAMzUhFSURMxEhETMRgAGA/gCAAYCAgICAAwD9AAMA/QAAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAhNTMVJREzETMRMxEBETMRIREzEQEAgP8AgICA/gCAAYCAgICAAQD/AAEA/wABAAIA/gACAP4AAAAAAAMAAAAAAoADgAADAAsAEwAAATUzFQERMxEzFSMVITUjNTMRMxEBAID+gICAgAGAgICAAQCAgP8AA4D9gICAgIACgPyAAAAAAAkAAAAAAoADgAADAAcACwAPABMAFwAbAB8AIwAAMREzESERMxEBNTMVMzUzFSU1MxUlNTMVMzUzFSU1MxUhNTMVgAGAgP4AgICA/wCA/wCAgID+AIABgIABgP6AAYD+gAGAgICAgICAgICAgICAgICAgIAABQAAAAACgAOAAAMABwALAA8AEwAAIREzEQE1MxUzNTMVJTUzFSE1MxUBAID/AICAgP4AgAGAgAKA/YACgICAgICAgICAgAAABQAAAAACgAOAAAUACQANABEAFwAAMREzFSEVATUzFT0BMxU9ATMVPQEhNSERgAIA/gCAgID+AAKAAQCAgAEAgICAgICAgICAgID/AAAAAAABAAAAAAGAA4AABwAAMREhFSERIRUBgP8AAQADgID9gIAAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAhNTMVJREzEQE1MxUlETMRATUzFQIAgP8AgP8AgP8AgP8AgICAgAEA/wABAICAgAEA/wABAICAAAAAAAEAAAAAAYADgAAHAAAxNSERITUhEQEA/wABgIACgID8gAAAAAUAAAIAAoADgAADAAcACwAPABMAABE1MxUhNTMVJTUzFTM1MxUlNTMVgAGAgP4AgICA/wCAAgCAgICAgICAgICAgIAAAQAA/4ACgAAAAAMAABU1IRUCgICAgAAAAQAAAwABAAOAAAMAABE1IRUBAAMAgIAAAwAAAAACgAKAAAMADQARAAA9ATMdATUhNSE1ITUzEQE1IRWAAYD+gAGAgP4AAYCAgICAgICAgP4AAgCAgAAAAAMAAAAAAoADgAADAAcAEQAAJREzEQE1IRUBETMRMxUjESEVAgCA/oABAP4AgICAAYCAAYD+gAGAgID+AAOA/oCA/wCAAAAAAAUAAAAAAoACgAADAAcACwAPABMAADM1IRU9ATMVIREzEQE1MxUlNSEVgAGAgP2AgAGAgP4AAYCAgICAgAGA/oABAICAgICAAAMAAAAAAoADgAADAAcAEQAANREzGQE1IRUBNSERIzUzETMRgAEA/wABgICAgIABgP6AAYCAgP4AgAEAgAGA/IAAAAAAAwAAAAACgAKAAAMADQARAAAzNSEVJREzFSE1MxEhFRE1IRWAAgD9gIABgID+AAGAgICAAYCAgP8AgAGAgIAAAAIAAAAAAgADgAALAA8AADMRIzUzNTMVIRUhGQE1IRWAgICAAQD/AAEAAgCAgICA/gADAICAAAAAAwAA/4ACgAKAAAMABwARAAAVNSEVAREzEQE1ITUhESE1IRECAP4AgAGA/oABgP6AAgCAgIABgAEA/wD/AICAAQCA/YAAAAAAAwAAAAACgAOAAAMABwAPAAAhETMRATUhFQERMxEzFSMRAgCA/oABAP4AgICAAgD+AAIAgID+AAOA/oCA/oAAAAIAAAAAAIADgAADAAcAADERMxEDNTMVgICAAoD9gAMAgIAAAAQAAP+AAoADAAADAAcACwAPAAAXNSEVJREzESERMxEDNTMVgAGA/gCAAYCAgICAgICAAQD/AAIA/gACgICAAAAFAAAAAAIAA4AAAwAHAAsADwAXAAAhNTMVJTUzFQM1MxU9ATMVAREzETMVIxEBgID/AICAgID+AICAgICAgICAAQCAgICAgP4AA4D+AID/AAAAAAACAAAAAAEAA4AAAwAHAAAzNTMVJREzEYCA/wCAgICAAwD9AAAEAAAAAAKAAoAAAwAHAA0AEQAAAREzERMRMxEhESEVIxEBNTMVAQCAgID9gAEAgAEAgAEAAQD/AP8AAgD+AAKAgP4AAgCAgAACAAAAAAKAAoAAAwAJAAAhETMRIREhFSERAgCA/YACAP6AAgD+AAKAgP4AAAQAAAAAAoACgAADAAcACwAPAAAzNSEVJREzESERMxEBNSEVgAGA/gCAAYCA/gABgICAgAGA/oABgP6AAYCAgAADAAD/gAKAAoAAAwAPABMAAAERMxEBETMVMxUjFSEVIRETNSEVAgCA/YCAgIABgP6AgAEAAQABAP8A/oADAICAgID/AAKAgIAAAAAAAwAA/4ACgAKAAAMABwATAAAZATMZATUhFRMRITUhNSM1MzUzEYABAID+gAGAgICAAQABAP8AAQCAgP2AAQCAgICA/QAAAAAAAwAAAAACgAKAAAMACwAPAAABNTMVAREzFTMVIxETNSEVAgCA/YCAgICAAQABgICA/oACgICA/oACAICAAAAAAAUAAAAAAoACgAADAAcACwAPABMAADE1IRU9ATMVJTUhFSU1MxU9ASEVAgCA/gABgP4AgAIAgICAgICAgICAgICAgIAAAgAAAAABgAOAAAMADwAAITUzFSURIzUzETMRMxUjEQEAgP8AgICAgICAgIABgIABAP8AgP6AAAACAAAAAAKAAoAAAwAJAAA1ETMRFTUhETMRgAGAgIACAP4AgIACAP2AAAAAAAUAAAAAAoACgAADAAcACwAPABMAACE1MxUlNTMVMzUzFSURMxEhETMRAQCA/wCAgID+AIABgICAgICAgICAgAGA/oABgP6AAAIAAAAAAoACgAADAA0AADURMxEVNTMRMxEzETMRgICAgICAAgD+AICAAQD/AAIA/YAAAAAJAAAAAAKAAoAAAwAHAAsADwATABcAGwAfACMAADE1MxUhNTMVJTUzFTM1MxUlNTMVJTUzFTM1MxUlNTMVITUzFYABgID+AICAgP8AgP8AgICA/gCAAYCAgICAgICAgICAgICAgICAgICAgICAgAAAAwAA/4ACgAKAAAMABwAPAAAXNSEVAREzEQE1ITUhETMRgAGA/gCAAYD+gAGAgICAgAGAAYD+gP8AgIABgP2AAAMAAAAAAoACgAAHAAsAEwAAMTUzNTMVIRUBNTMVPQEhNSEVIxWAgAGA/oCA/oACgICAgICAAQCAgICAgICAAAAFAAAAAAIAA4AAAwAHAAsADwATAAAhNSEVJREzEQE1MxU1ETMZATUhFQEAAQD+gID/AICAAQCAgIABAP8AAQCAgIABAP8AAQCAgAAAAQAAAAAAgAOAAAMAADERMxGAA4D8gAAABQAAAAACAAOAAAMABwALAA8AEwAAMTUhFTURMxkBNTMVJREzEQE1IRUBAICA/wCA/oABAICAgAEA/wABAICAgAEA/wABAICAAAAAAAQAAAKAAwADgAADAAcACwAPAAARNTMVITUhFSU1IRUhNTMVgAEAAQD+AAEAAQCAAoCAgICAgICAgIAAAAIAAAAAAIADgAADAAcAADERMxEDNTMVgICAAoD9gAMAgIAAAAMAAAAAAgADAAADAAcACwAAMzUhFSURMxkBNSEVgAGA/gCAAYCAgIACAP4AAgCAgAAAAAACAAAAAAIAAwAADwATAAAxNTMRIzUzNTMVMxUjESEVATUzFYCAgICAgAEA/wCAgAEAgICAgP8AgAKAgIAAAAAABQAAAQABgAKAAAMABwALAA8AEwAAETUzFTM1MxUlNTMVJTUzFTM1MxWAgID/AID/AICAgAEAgICAgICAgICAgICAAAAFAAAAAAKAA4AAEwAXABsAHwAjAAAhNSM1MzUjNTM1MxUzFSMVMxUjFQE1MxUzNTMVJTUzFSE1MxUBAICAgICAgICAgP8AgICA/gCAAYCAgICAgICAgICAgAKAgICAgICAgICAAAAAAAIAAAAAAIADgAADAAcAADERMxEDETMRgICAAYD+gAIAAYD+gAAAAAAFAAD/gAKAAwAABwALAA8AEwAbAAAFNSM1IRUjFRM1MxUhETMRATUzFSU1MzUzFTMVAQCAAYCAgID9gIABgID+AICAgICAgICAAQCAgAGA/oABAICAgICAgIAAAAMAAAAAAwADgAAHAAsADwAAAREhFSMVMxUXESERBxEhEQEAAQCAgID+AIADAAEAAYCAgICAAoD9gIADgPyAAAABAAABAAGAAwAABwAAGQEhNSE1IREBAP8AAYABAAEAgID+AAAKAAAAAAKAAoAAAwAHAAsADwATABcAGwAfACMAJwAAITUzFTM1MxUlNTMVMzUzFSU1MxUzNTMVJTUzFTM1MxUlNTMVMzUzFQEAgICA/gCAgID+AICAgP8AgICA/wCAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAAAAQAAAIACgAGAAAUAACU1ITUhEQIA/gACgICAgP8AAAABAIABAAIAAYAAAwAAEzUhFYABgAEAgIAAAAAAAwAAAAADAAOAAAUADQARAAABESERIxUFNSM1MxEhEQcRIREBAAEAgAEAgID+AIADAAEAAYD/AICAgIABgP2AgAOA/IAAAAAAAQAAAwACgAOAAAMAABE1IRUCgAMAgIAAAgAAAgABgAOAAAMABwAAATUjFQcRIREBAICAAYACgICAgAGA/oAAAAIAAP+AAoADAAADAA8AABU1IRUBESE1IREzESEVIRECgP6A/wABAIABAP8AgICAAQABAIABAP8AgP8AAAIAAAIAAQADgAAFAAkAABkBMxUzFQM1MxWAgICAAgABAICAAQCAgAABAAACAAEAA4AABwAAETUzNSM1IRGAgAEAAgCAgID+gAAAAAABAYADAAKAA4AAAwAAATUhFQGAAQADAICAAAAAAQAA/4ACgAMAAAkAABURMxEhETMRIRWAAYCA/gCAA4D9gAKA/QCAAAMAAAAAAoADAAADAA0AEQAAETUzFRMRIzUzNSM1IREzETMRgICAgIABAICAAgCAgP4AAYCAgID9AAMA/QAAAAABAAABgACAAgAAAwAAETUzFYABgICAAAACAID/gAIAAIAAAwAHAAAXNSEVPQEzFYABAICAgICAgIAAAAABAAACgACAA4AAAwAAGQEzEYACgAEA/wAAAAAAAgAAAgABgAOAAAMABwAAATUjFQcRIREBAICAAYACgICAgAGA/oAAAAoAAAAAAoACgAADAAcACwAPABMAFwAbAB8AIwAnAAAxNTMVMzUzFSU1MxUzNTMVJTUzFTM1MxUlNTMVMzUzFSU1MxUzNTMVgICA/wCAgID/AICAgP4AgICA/gCAgICAgICAgICAgICAgICAgICAgICAgICAgIAAAAgAAAAAAoADgAADAAkADQARABUAGQAdACEAADE1MxUhETMVMxUlETMRJTUzFSU1MxU1ETMRJREzESU1MxWAAQCAgP4AgAEAgP6AgID+AIABgICAgAEAgICAAQD/AICAgICAgIABAP8AgAEA/wCAgIAAAAAABwAAAAACgAOAAAMABwANABEAFQAZAB0AADE1MxU1ETMRBTUjESERATUzFTURMxElETMRJTUzFYCAAQCAAQD+gICA/gCAAYCAgICAAQD/AICAAQD+gAGAgICAAQD/AIABAP8AgICAAAAHAAAAAAKAA4AAAwAHAA0AEQAVAB0AIQAAMTUzFTURMxEFNSMRIREBNTMVNREzESE1MzUjNSERATUzFYCAAQCAAQD+gICA/gCAgAEAAQCAgICAAQD/AICAAQD+gAGAgICAAQD/AICAgP6AAQCAgAAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVPQEzFSERMxkBNTMVPQEzFQM1MxWAAYCA/YCAgICAgICAgICAAQD/AAEAgICAgIABAICAAAADAAAAAAKAA4AACwAPABMAADERMxUhNTMRIxEhGQE1IRUBNSEVgAGAgID+gAGA/gABAAIAgID+AAEA/wACAICAAQCAgAAAAAADAAAAAAKAA4AACwAPABMAADERMxUhNTMRIxEhGQE1IRUDNSEVgAGAgID+gAGAgAEAAgCAgP4AAQD/AAIAgIABAICAAAUAAAAAAoADgAALAA8AEwAXABsAADERMxUhNTMRIxEhGQE1IRUlNTMVITUzFSU1IRWAAYCAgP6AAYD+AIABgID+AAGAAgCAgP4AAQD/AAIAgICAgICAgICAgAAABQAAAAADAAOAAAsADwAXABsAHwAAMREzFSE1MxEjESERAzUzHQE1ITUhFSMVATUhFSE1MxWAAYCAgP6AgIABAAEAgP6AAQABAIACAICA/gABAP8AAoCAgICAgICAAQCAgICAAAQAAAAAAoADgAALAA8AEwAXAAAxETMVITUzESMRIRkBNSEVATUzFTM1MxWAAYCAgP6AAYD+gICAgAIAgID+AAEA/wACAICAAQCAgICAAAAAAwAAAAACgAOAAAsADwATAAAxETMVITUzESMRIRkBNSEVATUzFYABgICA/oABgP8AgAIAgID+AAEA/wACAICAAQCAgAABAAAAAAKAA4AAFQAAMREzFTM1IzUhFSEVMxUjESEVIREjEYCAgAIA/wCAgAEA/oCAAwCAgICAgID+gIACAP4AAAAAAAcAAP+AAoADgAADAAcACwAPABMAFwAbAAAFNSEVPQEzFSU1IRU9ATMVIREzEQE1MxUlNSEVAQABAID+AAGAgP2AgAGAgP4AAYCAgICAgICAgICAgIACAP4AAYCAgICAgAAAAAACAAAAAAKAA4AACwAPAAAxESEVIRUhFSEVIRUBNSEVAoD+AAEA/wACAP2AAQACgICAgICAAwCAgAAAAAACAAAAAAKAA4AACwAPAAAxESEVIRUhFSEVIRUBNSEVAoD+AAEA/wACAP8AAQACgICAgICAAwCAgAAAAAAFAAAAAAKAA4AACQANABEAFQAZAAAxETMVIRUhFSEVATUhFSU1MxUhNTMVJTUhFYABAP8AAgD+AAGA/gCAAYCA/gABgAIAgICAgAIAgICAgICAgICAgAAAAwAAAAACgAOAAAsADwATAAAxESEVIRUhFSEVIRUBNTMVMzUzFQKA/gABAP8AAgD+AICAgAKAgICAgIADAICAgIAAAAACAAAAAAIAA4AACwAPAAAzNTMRIzUhFSMRMxUBNSEVgICAAYCAgP4AAQCAAYCAgP6AgAMAgIAAAAIAgAAAAoADgAALAA8AADM1MxEjNSEVIxEzFQM1IRWAgIABgICAgAEAgAGAgID+gIADAICAAAAABAAAAAACgAOAAAsADwATABcAADM1MxEjNSEVIxEzFQE1MxUhNTMVJTUhFYCAgAGAgID+AIABgID+AAGAgAGAgID+gIACgICAgICAgIAAAAADAAAAAAGAA4AACwAPABMAADE1MxEjNSEVIxEzFQE1MxUzNTMVgIABgICA/oCAgICAAYCAgP6AgAMAgICAgAAAAgAAAAADAAOAAAMAEwAAJREzEQURIzUzESEVIREzFSMRIRUCgID9gICAAgD+gICAAYCAAoD9gIABgIABgID/AID/AIAAAAAABQAAAAADAAOAAAMACwAVABkAHQAAATUzFQERMxEzFSMRITUjNTMRIzUhEQE1IRUhNTMVAQCA/oCAgIABgICAgAEA/gABAAEAgAEAgID/AAMA/wCA/oCAgAGAgP0AAwCAgICAAAUAAAAAAoADgAADAAcACwAPABMAADM1IRUlETMRIREzEQE1IRUBNSEVgAGA/gCAAYCA/gABgP4AAQCAgIABgP6AAYD+gAGAgIABAICAAAAABQAAAAACgAOAAAMABwALAA8AEwAAMzUhFSURMxEhETMRATUhFQM1IRWAAYD+AIABgID+AAGAgAEAgICAAYD+gAGA/oABgICAAQCAgAAAAAAHAAAAAAKAA4AAAwAHAAsADwATABcAGwAAMzUhFSURMxEhETMRATUhFSU1MxUhNTMVJTUhFYABgP4AgAGAgP4AAYD+AIABgID+AAGAgICAAYD+gAGA/oABgICAgICAgICAgIAABwAAAAADAAOAAAMABwALAA8AFwAbAB8AADM1IRUlETMRIREzEQE1Mx0BNSE1IRUjFQE1IRUhNTMVgAGA/gCAAYCA/YCAAQABAID+gAEAAQCAgICAAYD+gAGA/oACAICAgICAgIABAICAgIAABgAAAAACgAOAAAMABwALAA8AEwAXAAAzNSEVJREzESERMxEBNSEVJTUzFSE1MxWAAYD+AIABgID+AAGA/gCAAYCAgICAAgD+AAIA/gACAICAgICAgIAAAAkAAACAAoADAAADAAcACwAPABMAFwAbAB8AIwAAPQEzFSE1MxUlNTMVMzUzFSU1MxUlNTMVMzUzFSU1MxUhNTMVgAGAgP4AgICA/wCA/wCAgID+AIABgICAgICAgICAgICAgICAgICAgICAgICAgAADAAAAAAKAA4AAAwANABcAAAERMxEBNSMRMxEzFSEVNREjNSE1IRUzEQEAgP8AgICAAQCA/wABgIABAAGA/oD/AIACgP4AgICAAgCAgID9gAAAAAAEAAAAAAKAA4AAAwAHAAsADwAAMzUhFSURMxEhETMRATUhFYABgP4AgAGAgP2AAQCAgIACAP4AAgD+AAKAgIAABAAAAAACgAOAAAMABwALAA8AADM1IRUlETMRIREzEQE1IRWAAYD+AIABgID/AAEAgICAAgD+AAIA/gACgICAAAYAAAAAAoADgAADAAcACwAPABMAFwAAMzUhFSURMxEhETMRATUzFSE1MxUlNSEVgAGA/gCAAYCA/YCAAYCA/gABgICAgAGA/oABgP6AAgCAgICAgICAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAzNSEVJREzESERMxEBNTMVMzUzFYABgP4AgAGAgP4AgICAgICAAgD+AAIA/gACgICAgIAAAAAABgAAAAACgAOAAAMABwALAA8AEwAXAAAhETMRATUzFTM1MxUlNTMVITUzFQE1IRUBAID/AICAgP4AgAGAgP2AAQABgP6AAYCAgICAgICAgIABAICAAAAAAAMAAP+AAoADAAADAAcAEwAAJREzEQE1IRUBETMRMxUjESEVIRUCAID+gAEA/gCAgIABgP6AgAGA/oABgICA/YADgP8AgP8AgIAAAAAEAAAAAAKAA4AAAwANABEAFQAAPQEzHQE1ITUhNSE1MxEBNSEVATUhFYABgP6AAYCA/gABgP4AAQCAgICAgICAgP4AAgCAgAEAgIAABAAAAAACgAOAAAMADQARABUAAD0BMx0BNSE1ITUhNTMRATUhFQM1IRWAAYD+gAGAgP4AAYCAAQCAgICAgICAgP4AAgCAgAEAgIAAAAYAAAAAAoADgAADAA0AEQAVABkAHQAAPQEzHQE1ITUhNSE1MxEBNSEVJTUzFSE1MxUlNSEVgAGA/oABgID+AAGA/gCAAYCA/gABgICAgICAgICA/gACAICAgICAgICAgIAAAAAGAAAAAAMAA4AAAwANABEAGQAdACEAAD0BMx0BNSE1ITUhNTMRATUzHQE1ITUhFSMVATUhFSE1MxWAAYD+gAGAgP2AgAEAAQCA/oABAAEAgICAgICAgICA/gACgICAgICAgIABAICAgIAAAAAFAAAAAAKAA4AAAwANABEAFQAZAAA9ATMdATUhNSE1ITUzEQE1IRUBNTMVMzUzFYABgP6AAYCA/gABgP6AgICAgICAgICAgID+AAIAgIABAICAgIAAAAAABAAAAAACgAOAAAMADQARABUAAD0BMx0BNSE1ITUhNTMRATUhFQE1MxWAAYD+gAGAgP4AAYD/AICAgICAgICAgP4AAgCAgAEAgIAAAAQAAAAAAoACgAADABUAGQAdAAA9ATMdATUzNSM1MzUzFTM1MxEhFSEVATUzFTM1MxWAgICAgICA/wABAP4AgICAgICAgICAgICAgP8AgIACAICAgIAAAAAHAAD/gAKAAwAAAwAHAAsADwATABcAGwAABTUhFT0BMxUlNSEVPQEzFSERMxEBNTMVJTUhFQEAAQCA/gABgID9gIABgID+AAGAgICAgICAgICAgICAAYD+gAEAgICAgIAAAAAABAAAAAACgAOAAAMADQARABUAADM1IRUlETMVITUzESEVETUhFQE1IRWAAgD9gIABgID+AAGA/gABAICAgAGAgID/AIABgICAAQCAgAAAAAAEAAAAAAKAA4AAAwANABEAFQAAMzUhFSURMxUhNTMRIRURNSEVAzUhFYACAP2AgAGAgP4AAYCAAQCAgIABgICA/wCAAYCAgAEAgIAABgAAAAACgAOAAAMADQARABUAGQAdAAAzNSEVJREzFSE1MxEhFRE1IRUlNTMVITUzFSU1IRWAAgD9gIABgID+AAGA/gCAAYCA/gABgICAgAGAgID/AIABgICAgICAgICAgIAAAAUAAAAAAoADgAADAA0AEQAVABkAADM1IRUlETMVITUzESEVETUhFQE1MxUzNTMVgAIA/YCAAYCA/gABgP6AgICAgICAAYCAgP8AgAGAgIABAICAgIAAAAACAAAAAAEAA4AAAwAHAAAzETMRATUhFYCA/wABAAKA/YADAICAAAAAAgAAAAABAAOAAAMABwAAMREzEQM1IRWAgAEAAoD9gAMAgIAABAAAAAACgAOAAAMABwALAA8AACERMxEBNTMVITUzFSU1IRUBAID+gIABgID+AAGAAoD9gAKAgICAgICAgAAAAAMAgAAAAgADgAADAAcACwAAIREzEQE1MxUzNTMVAQCA/wCAgIACgP2AAwCAgICAAAQAAAAAAwADgAADAA8AEwAXAAAhETMRIREzFSE1IRUjFSEZATUhFSE1MxUCAID9gIABAAEAgP6AAQABAIACAP4AAwCAgICA/gADAICAgIAABQAAAAACgAOAAAMABwALAA8AEwAAMzUhFSURMxEhETMRATUhFQE1IRWAAYD+AIABgID+AAGA/gABAICAgAGA/oABgP6AAYCAgAEAgIAAAAAFAAAAAAKAA4AAAwAHAAsADwATAAAzNSEVJREzESERMxEBNSEVAzUhFYABgP4AgAGAgP4AAYCAAQCAgIABgP6AAYD+gAGAgIABAICAAAAAAAcAAAAAAoADgAADAAcACwAPABMAFwAbAAAzNSEVJREzESERMxEBNSEVJTUzFSE1MxUlNSEVgAGA/gCAAYCA/gABgP4AgAGAgP4AAYCAgIABgP6AAYD+gAGAgICAgICAgICAgAAHAAAAAAMAA4AAAwAHAAsADwAXABsAHwAAMzUhFSURMxEhETMRATUzHQE1ITUhFSMVATUhFSE1MxWAAYD+AIABgID9gIABAAEAgP6AAQABAICAgIABgP6AAYD+gAIAgICAgICAgAEAgICAgAAGAAAAAAKAA4AAAwAHAAsADwATABcAADM1IRUlETMRIREzEQE1IRUBNTMVMzUzFYABgP4AgAGAgP4AAYD+gICAgICAgAGA/oABgP6AAYCAgAEAgICAgAAAAwAAAIACgAMAAAMABwALAAAlNTMVATUhFQE1MxUBAID+gAKA/oCAgICAAQCAgAEAgIAAAAMAAAAAAoACgAADAA0AFwAAATUzFQE1IxEzETMVIRU1ESM1ITUhFTMRAQCA/wCAgIABAID/AAGAgAEAgID/AIABgP8AgICAAQCAgID+gAAAAwAAAAACgAOAAAMACQANAAA1ETMRFTUhETMRATUhFYABgID9gAEAgAIA/gCAgAIA/YADAICAAAADAAAAAAKAA4AAAwAJAA0AADURMxEVNSERMxEBNSEVgAGAgP8AAQCAAgD+AICAAgD9gAMAgIAAAAUAAAAAAoADgAADAAkADQARABUAADURMxEVNSERMxEBNTMVITUzFSU1IRWAAYCA/YCAAYCA/gABgIABgP6AgIABgP4AAoCAgICAgICAAAAABAAAAAACgAOAAAMACQANABEAADURMxEVNSERMxEBNTMVMzUzFYABgID+AICAgIACAP4AgIACAP2AAwCAgICAAAQAAP+AAoADgAADAAcADwATAAAXNSEVAREzEQE1ITUhETMRATUhFYABgP4AgAGA/oABgID9gAEAgICAAYABgP6A/wCAgAGA/YADAICAAAAAAwAA/4ACgAOAAAMABwATAAAlETMRATUhFQERMxEzFSMRIRUhFQIAgP6AAQD+AICAgAGA/oCAAYD+gAGAgID9gAQA/oCA/wCAgAAAAAUAAP+AAoADgAADAAcADwATABcAABc1IRUBETMRATUhNSERMxEBNTMVMzUzFYABgP4AgAGA/oABgID+AICAgICAgAGAAYD+gP8AgIABgP2AAwCAgICAAAACAAAAAAKAA4AAAwATAAA1ETMRFTUzESM1IRUhFTMVIxEhFYCAgAIA/wCAgAEAgAKA/YCAgAKAgICAgP6AgAAABQAAAAACgAKAAAMABwALAA8AGwAAMzUzFTM1IRUlETMZATUzFRkBMxUzNSM1IREhFYCAgAEA/YCAgICAgAEA/wCAgICAgAGA/oABgICA/oABgICAgP6AgAAAAAAHAAAAAAKAA4AAAwAHAAsADwATABcAGwAAIREzEQE1MxUzNTMVJTUzFSE1MxUBNTMVMzUzFQEAgP8AgICA/gCAAYCA/gCAgIABgP6AAYCAgICAgICAgIABAICAgIAAAAABAAABgAMAAgAAAwAAETUhFQMAAYCAgAACAAACAAEAA4AAAwAHAAAZATMZATUzFYCAAgABAP8AAQCAgAACAAACAAEAA4AAAwAHAAARNTMVNREzEYCAAgCAgIABAP8AAAACAAD/gAEAAQAAAwAHAAAVNTMVNREzEYCAgICAgAEA/wAAAAACAAACAAEAA4AAAwAHAAATNTMVJREzEYCA/wCAAgCAgIABAP8AAAAABAAAAgACAAOAAAMABwALAA8AABkBMxEzETMRATUzFTM1MxWAgID/AICAgAIAAQD/AAEA/wABAICAgIAABAAAAgACAAOAAAMABwALAA8AABE1MxUzNTMVJREzETMRMxGAgID/AICAgAIAgICAgIABAP8AAQD/AAAABAAA/4ACAAEAAAMABwALAA8AABU1MxUzNTMVJREzETMRMxGAgID/AICAgICAgICAgAEA/wABAP8AAAAAAQAAAAABgAMAAAsAADMRIzUzETMRMxUjEYCAgICAgAGAgAEA/wCA/oAAAAABAAABgAEAAoAAAwAAGQEhEQEAAYABAP8AAAAAAwAAAAACgACAAAMABwALAAAxNTMVMzUzFTM1MxWAgICAgICAgICAgAAAAAADAAAAAAEAAYAAAwAHAAsAADM1MxUlNTMVPQEzFYCA/wCAgICAgICAgICAAAMAAAAAAQABgAADAAcACwAAMTUzFT0BMxUlNTMVgID/AICAgICAgICAgAAAAwAAAAACgAOAAAMAFwAbAAAhNSEVJTUjNTM1IzUzNTMVIRUhFSEVIRURNSEVAQABgP4AgICAgIABAP8AAQD/AAGAgICAgICAgICAgICAgAKAgIAAAgAAAgAEgAOAAAcAEwAAExEjNSEVIxEhESERIxEjFSM1IxGAgAGAgAEAAoCAgICAAgABAICA/wABgP6AAQCAgP8AAAAAACABhgABAAAAAAAAASUCTAABAAAAAAABAAkDhgABAAAAAAACAAcDoAABAAAAAAADABEDzAABAAAAAAAEABEEAgABAAAAAAAFAAsELAABAAAAAAAGAAkETAABAAAAAAAHAGMFHgABAAAAAAAIABYFsAABAAAAAAAJAAUF0wABAAAAAAAKASUIJQABAAAAAAALAB8JiwABAAAAAAAMABEJzwABAAAAAAANACgKMwABAAAAAAAOAC4KugABAAAAAAATABsLIQADAAEECQAAAkoAAAADAAEECQABABIDcgADAAEECQACAA4DkAADAAEECQADACIDqAADAAEECQAEACID3gADAAEECQAFABYEFAADAAEECQAGABIEOAADAAEECQAHAMYEVgADAAEECQAIACwFggADAAEECQAJAAoFxwADAAEECQAKAkoF2QADAAEECQALAD4JSwADAAEECQAMACIJqwADAAEECQANAFAJ4QADAAEECQAOAFwKXAADAAEECQATADYK6QBUAGgAaQBzACAAIgBNAGkAbgBlAGMAcgBhAGYAdAAiACAAZgBvAG4AdAAgAHcAYQBzACAAYQBkAGEAcAB0AGUAZAAgAGkAbgB0AG8AIABUAHIAdQBlAFQAeQBwAGUAIABmAGkAbABlACAAYgB5ACAAbQBlACAAKABEAGoARABDAEgAKQAuAA0ACgANAAoAVABoAGkAcwAgACIATQBpAG4AZQBjAHIAYQBmAHQAIgAgAGYAbwBuAHQAIABpAHMAIAB1AG4AZABlAHIAIABDAHIAZQBhAHQAaQB2AGUAIABDAG8AbQBtAG8AbgBzACAATABpAGMAZQBuAHMAZQAgACgAUwBoAGEAcgBlACAAQQBsAGkAawBlACkALgANAAoADQAKAFQAaABlACAAIgBEAGoARABDAEgAIgAgAG4AYQBtAGUAIABpAHMAIABvAHcAbgAgAGIAeQAgAG0AZQAgACgAZABqAGQAYwBoAC4AYwBvAG0AKQAuAA0ACgANAAoAVABoAGUAIAAiAE0AaQBuAGUAYwByAGEAZgB0ACIAIABmAG8AbgB0ACAAcwB0AHkAbABlACAAdwBhAHMAIABtAGEAZABlACAAYgB5ACAATgBvAHQAYwBoAC4ADQAKAA0ACgBUAGgAZQAgACIATQBpAG4AZQBjAHIAYQBmAHQAIgAgAGcAYQBtAGUAIABpAHMAIABvAHcAbgAgAGIAeQAgAE0AbwBqAGEAbgBnACAAUwBwAGUAYwBpAGYAaQBjAGEAdABpAG8AbgBzAC4AAFRoaXMgIk1pbmVjcmFmdCIgZm9udCB3YXMgYWRhcHRlZCBpbnRvIFRydWVUeXBlIGZpbGUgYnkgbWUgKERqRENIKS4NCg0KVGhpcyAiTWluZWNyYWZ0IiBmb250IGlzIHVuZGVyIENyZWF0aXZlIENvbW1vbnMgTGljZW5zZSAoU2hhcmUgQWxpa2UpLg0KDQpUaGUgIkRqRENIIiBuYW1lIGlzIG93biBieSBtZSAoZGpkY2guY29tKS4NCg0KVGhlICJNaW5lY3JhZnQiIGZvbnQgc3R5bGUgd2FzIG1hZGUgYnkgTm90Y2guDQoNClRoZSAiTWluZWNyYWZ0IiBnYW1lIGlzIG93biBieSBNb2phbmcgU3BlY2lmaWNhdGlvbnMuAABNAGkAbgBlAGMAcgBhAGYAdAAATWluZWNyYWZ0AABSAGUAZwB1AGwAYQByAABSZWd1bGFyAABNAGkAbgBlAGMAcgBhAGYAdAAgAFIAZQBnAHUAbABhAHIAAE1pbmVjcmFmdCBSZWd1bGFyAABNAGkAbgBlAGMAcgBhAGYAdAAgAFIAZQBnAHUAbABhAHIAAE1pbmVjcmFmdCBSZWd1bGFyAABWAGUAcgBzAGkAbwBuACAAMQAuADAAAFZlcnNpb24gMS4wAABNAGkAbgBlAGMAcgBhAGYAdAAATWluZWNyYWZ0AABUAGgAZQAgACIARABqAEQAQwBIACIAIABuAGEAbQBlACAAaQBzACAAbwB3AG4AIABiAHkAIABtAGUAIAAoAGQAagBkAGMAaAAuAGMAbwBtACkALgANAAoADQAKAFQAaABlACAAIgBNAGkAbgBlAGMAcgBhAGYAdAAiACAAZwBhAG0AZQAgAGkAcwAgAG8AdwBuACAAYgB5ACAATQBvAGoAYQBuAGcAIABTAHAAZQBjAGkAZgBpAGMAYQB0AGkAbwBuAHMALgAAVGhlICJEakRDSCIgbmFtZSBpcyBvd24gYnkgbWUgKGRqZGNoLmNvbSkuDQoNClRoZSAiTWluZWNyYWZ0IiBnYW1lIGlzIG93biBieSBNb2phbmcgU3BlY2lmaWNhdGlvbnMuAABGAG8AbgB0AHMAdAByAHUAYwB0ACAAYgB5ACAARgBvAG4AdABTAGgAbwBwAABGb250c3RydWN0IGJ5IEZvbnRTaG9wAABEAGoARABDAEgAAERqRENIAABUAGgAaQBzACAAIgBNAGkAbgBlAGMAcgBhAGYAdAAiACAAZgBvAG4AdAAgAHcAYQBzACAAYQBkAGEAcAB0AGUAZAAgAGkAbgB0AG8AIABUAHIAdQBlAFQAeQBwAGUAIABmAGkAbABlACAAYgB5ACAAbQBlACAAKABEAGoARABDAEgAKQAuAA0ACgANAAoAVABoAGkAcwAgACIATQBpAG4AZQBjAHIAYQBmAHQAIgAgAGYAbwBuAHQAIABpAHMAIAB1AG4AZABlAHIAIABDAHIAZQBhAHQAaQB2AGUAIABDAG8AbQBtAG8AbgBzACAATABpAGMAZQBuAHMAZQAgACgAUwBoAGEAcgBlACAAQQBsAGkAawBlACkALgANAAoADQAKAFQAaABlACAAIgBEAGoARABDAEgAIgAgAG4AYQBtAGUAIABpAHMAIABvAHcAbgAgAGIAeQAgAG0AZQAgACgAZABqAGQAYwBoAC4AYwBvAG0AKQAuAA0ACgANAAoAVABoAGUAIAAiAE0AaQBuAGUAYwByAGEAZgB0ACIAIABmAG8AbgB0ACAAcwB0AHkAbABlACAAdwBhAHMAIABtAGEAZABlACAAYgB5ACAATgBvAHQAYwBoAC4ADQAKAA0ACgBUAGgAZQAgACIATQBpAG4AZQBjAHIAYQBmAHQAIgAgAGcAYQBtAGUAIABpAHMAIABvAHcAbgAgAGIAeQAgAE0AbwBqAGEAbgBnACAAUwBwAGUAYwBpAGYAaQBjAGEAdABpAG8AbgBzAC4AAFRoaXMgIk1pbmVjcmFmdCIgZm9udCB3YXMgYWRhcHRlZCBpbnRvIFRydWVUeXBlIGZpbGUgYnkgbWUgKERqRENIKS4NCg0KVGhpcyAiTWluZWNyYWZ0IiBmb250IGlzIHVuZGVyIENyZWF0aXZlIENvbW1vbnMgTGljZW5zZSAoU2hhcmUgQWxpa2UpLg0KDQpUaGUgIkRqRENIIiBuYW1lIGlzIG93biBieSBtZSAoZGpkY2guY29tKS4NCg0KVGhlICJNaW5lY3JhZnQiIGZvbnQgc3R5bGUgd2FzIG1hZGUgYnkgTm90Y2guDQoNClRoZSAiTWluZWNyYWZ0IiBnYW1lIGlzIG93biBieSBNb2phbmcgU3BlY2lmaWNhdGlvbnMuAABoAHQAdABwADoALwAvAGYAbwBuAHQAcwB0AHIAdQBjAHQALgBmAG8AbgB0AHMAaABvAHAALgBjAG8AbQAvAABodHRwOi8vZm9udHN0cnVjdC5mb250c2hvcC5jb20vAABoAHQAdABwADoALwAvAGQAagBkAGMAaAAuAGMAbwBtAC8AAGh0dHA6Ly9kamRjaC5jb20vAABDAHIAZQBhAHQAaQB2AGUAIABDAG8AbQBtAG8AbgBzACAAQQB0AHQAcgBpAGIAdQB0AGkAbwBuACAAUwBoAGEAcgBlACAAQQBsAGkAawBlAABDcmVhdGl2ZSBDb21tb25zIEF0dHJpYnV0aW9uIFNoYXJlIEFsaWtlAABoAHQAdABwADoALwAvAGMAcgBlAGEAdABpAHYAZQBjAG8AbQBtAG8AbgBzAC4AbwByAGcALwBsAGkAYwBlAG4AcwBlAHMALwBiAHkALQBzAGEALwAzAC4AMAAvAABodHRwOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS1zYS8zLjAvAABNAGkAbgBlAGMAcgBhAGYAdAAgAGkAcwAgAGoAdQBzAHQAIABhAHcAZQBzAG8AbQBlACAAIQAATWluZWNyYWZ0IGlzIGp1c3QgYXdlc29tZSAhAAAAAgAAAAAAAABlADMAAAAAAAAAAAAAAAAAAAAAAAAAAADQAAABAgEDAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQCjAIQAhQC9AJYA6ACOAIsAnQCpAKQBBACKANoAgwCTAQUBBgCNAQcAiADDAN4BCACeAKoA9QD0APYAogCtAMkAxwCuAGIAYwCQAGQAywBlAMgAygDPAMwAzQDOAOkAZgDTANAA0QCvAGcA8ACRANYA1ADVAGgA6wDtAGoAaQBrAG0AbABuAKAAbwBxAHAAcgBzAHUAdAB2AHcAeAB6AHkAewB9AHwAuAChAH8AfgCAAIEA7ADuALoAsACxALsAswC2ALcAxAEJALQAtQDFAIIAhwCrAL4AvwEKAIwGZ2x5cGgxB3VuaTAwMEQHdW5pMDBBRAd1bmkwMEIyB3VuaTAwQjMHdW5pMDBCNQd1bmkwMEI5DXF1b3RlcmV2ZXJzZWQERXVybwAAAAH//wACAAEAAAAOAAAAGAAAAAAAAgABAAEAzwABAAQAAAACAAAAAAABAAAAAMw9os8AAAAAyO86mAAAAADI8I+a",0),new android.os.Environment.getExternalStorageDirectory()+"/minecraft.ttf");
           font=new android.graphics.Typeface.createFromFile(new android.os.Environment.getExternalStorageDirectory()+"/minecraft.ttf");
                  function writeFileFromByteArray(byteArray,path){
	                     var fontFile=new java.io.File(path);
	if(fontFile.exists())
		    fontFile.delete();
	              fontFile.createNewFile();
	
	                    var fontStream=new java.io.FileOutputStream(fontFile);
	                        fontStream.write(byteArray);
	                             fontStream.close();
	}
	
//ENGLISH
//BECAUSE I WORKED HARD ON THIS MOD, IM NOT ALLOWING YOU TO USE A PART OF THE CODE, ESPECIALLY THE GUARDIAN MODEL. EVEN IF YOU ARE MY FRIEND.
//Mike Alpha Delta Echo Bravo Yankee Bravo Alpha Golf Alpha Sierra
//Status : 9731 Line of Codes (if the code passed 5000 lines it is restricted to use a part of the code for your mod.)
//Protected.

Guardian1s = false;
ElderGuardian1s = false;

var var2 = 2;

var hurt1 = false;
var ehurt1 = false;

var Guardian1;
var ElderGuardian1;
var esnowball=[];
var snowball=[];
function entityRemovedHook(entity){
if(entity==Guardian1){
			Level.dropItem(Entity.getX(Guardian1),Entity.getY(Guardian1)+1,Entity.getZ(Guardian1),10,19,2,0);
Guardian1s=false;
}
if(entity==ElderGuardian1){
	Level.dropItem(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1)+1,Entity.getZ(ElderGuardian1),10,19,2,0);
ElderGuardian1s=false;
}
}

function useItem(x, y, z, itemId, block, side) {
	if(b==true){
    if (itemId == 505) {
        if(Guardian1s==false)
{
Guardian1= Level.spawnMob(x,y+1,z,17,"mob/guardian.png");
Entity.setRenderType(Guardian1,GuardianRenderType.renderType);
Entity.setHealth(Guardian1, 40); 
Guardian1s=true;
}
}
if(itemId == 505){
if(Guardian1s==true)
{
clientMessage("You can't spawn more Guardians!");
}
}
if (itemId == 506) {
        if(ElderGuardian1s==false)
{
ElderGuardian1= Level.spawnMob(x,y+1,z,17,"mob/guardian_elder.png");
Entity.setRenderType(ElderGuardian1,ElderGuardianRenderType.renderType);
Entity.setHealth(ElderGuardian1, 90); 
ElderGuardian1s=true;
}
}
if(itemId == 506){
if(ElderGuardian1s==true)
{
clientMessage("You can't spawn more Elder Guardians!");
}
}
}
if(b==false && itemId == 506 || b==false && itemId == 505){
	clientMessage(ChatColor.RED+"This item is locked! get the license first!")
	}
	
}

var stic=0;
var b = true;


ModPE.setItem(505,"empty_armor_slot_boots",0,"Spawn Guardian");
ModPE.setItem(506,"empty_armor_slot_chestplate",0,"Spawn Elder Guardian");
var tick1 = 1;
var etick1 = 1;
var stay1 = 1;
var estay1 = 1;


ModPE.overrideTexture("images/mob/guardian.png","https://dl.dropboxusercontent.com/s/vbx3xbmnv5wrv04/guardian.png?dl=0");       
ModPE.overrideTexture("images/mob/guardian_elder.png","https://dl.dropboxusercontent.com/s/j4jnmy6qhg05l6b/guardian_elder.png?dl=0");       

function newLevel(){
	if(b==true){
clientMessage(ChatColor.GREEN+"WaterGuardianPE by BagasMC");
clientMessage(ChatColor.GOLD+   " Current Version : v3.5b010");
Player.addItemCreativeInv(505,1, 0);
Item.setCategory(505,3);
Player.addItemCreativeInv(506,1, 0);
Item.setCategory(506,3);
}
var ctx = com.mojang.minecraftpe.MainActivity.currentMainActivity.get();
var file = java.io.File(path);
if(file.exists() == false){
	b = false;
		return;
		}
if(file.exists() == true){
	b = true;
	 clientMessage(ChatColor.GREEN+"[Success] Successfully Installed the License!");
	clientMessage(ChatColor.GREEN+"[Success] Mod by BagasMC!");
}
}

var path=android.os.Environment.getExternalStorageDirectory().getAbsolutePath()+"/games/com.mojang/Mod/BagasC.txt";

function procCmd(c)
{
var cmd = c.split(" ");
if(cmd[0]=="download"){
 var path=android.os.Environment.getExternalStorageDirectory().getAbsolutePath()+"/games/com.mojang/Mod/";
if(!java.io.File(path).exists())
{
	try
   {
		java.io.File(path).mkdirs();
		ModPE.downloadFile("BagasC.txt","https://dl.dropboxusercontent.com/s/d6pcg12goxbcfbn/BagasC.txt?dl=0");
		clientMessage(ChatColor.GREEN+"[Done] License Downloaded! Please type /verify to Verify the license!")
		}
	catch(err)
   {
		print(err);
		}
}
}
	if(cmd[0] == "summon")
	{
if(cmd[1] =="Chicken")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 10);
}
else if(cmd[1] =="Cow")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 11);
}
else if(cmd[1] =="Pig")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 12);
}
else if(cmd[1] =="Sheep")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 13);
}
else if(cmd[1] =="Wolf")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 14);
}
else if(cmd[1] =="Villager")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 15);
}
else if(cmd[1] =="Mooshroom")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 16);
}
else if(cmd[1] =="Zombie"&&cmd[2]==undefined)
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 32);
}
else if(cmd[1] =="Creeper")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 33);
}
else if(cmd[1] =="Skeleton")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 34);
}
else if(cmd[1] =="Spider")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 35);
}
else if(cmd[1] =="Zombie" && cmd[2]=="Pigman")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 36);
}
else if(cmd[1] =="Slime")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 37);
}
else if(cmd[1] =="Enderman")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 38);
}
else if(cmd[1] =="Silverfish")
{
Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(), 39);
}
else if(cmd[1] =="Guardian"){
      if(Guardian1s==false)
{
Guardian1= Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(),17,"mob/guardian.png");
Entity.setRenderType(Guardian1,GuardianRenderType.renderType);
Entity.setHealth(Guardian1, 40); 
Guardian1s=true;
}
}
else if(cmd[1] =="Elder" && cmd[2] == "Guardian"){
      if(ElderGuardian1s==false)
{
ElderGuardian1= Level.spawnMob(Player.getX(), Player.getY(), Player.getZ(),17,"mob/guardian_elder.png");
Entity.setRenderType(ElderGuardian1,ElderGuardianRenderType.renderType);
Entity.setHealth(ElderGuardian1, 80); 
ElderGuardian1s=true;
}
}
}
if(cmd[0]=="debugMode" && cmd[1]=="true"){
	debugMode=true;
}
if(cmd[0]=="debugMode" && cmd[1]=="false"){
	debugMode=false;
	}
 if(cmd[0]=="verify"){
     var file = java.io.File(path);
     var path=android.os.Environment.getExternalStorageDirectory().getAbsolutePath()+"/games/com.mojang/Mod/";
     if(java.io.File(path).exists()){
        clientMessage(ChatColor.GREEN+"[Verified] Verified the License! Have fun!");
        b=true;
 }
      else {
         clientMessage(ChatColor.RED+"No License yet.....")
         b=false;
         return;
         }
 }
 }

 ModPE.downloadFile=function(filename,url)
{
	var file=new java.io.File(android.os.Environment.getExternalStorageDirectory().getAbsolutePath()+"/games/com.mojang/Mod/"+filename);
	file.createNewFile();
	var fos=new java.io.FileOutputStream(file);
	var response=android.net.http.AndroidHttpClient.newInstance("ModPE.downloadFile()").execute(new org.apache.http.client.methods.HttpGet(url)).getEntity().writeTo(fos);
	fos.close();
	};
var webWindow=null;
function ShowGUI(){
	activity.runOnUiThread(new java.lang.Runnable({
		run: function(){
			webWindow=new android.widget.PopupWindow();
			var webView=new android.webkit.WebView(activity);
			webView.getSettings().setJavaScriptEnabled(true);
			webView.getSettings().setUserAgentString("Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.4) Gecko/20100101 Firefox/4.0");
			webView.loadUrl("https://www.google.com");
			webWindow.setContentView(webView);
			webWindow.setWidth(0);
			webWindow.setHeight(0);
			webWindow.showAtLocation(activity.getWindow().getDecorView(),android.view.Gravity.TOP | android.view.Gravity.LEFT,-100,-100);
			}
		}));
	}
function HideGUI()
{
	activity.runOnUiThread(new java.lang.Runnable(
  { 
		run: function()
    {
			if(webWindow!=null) 
      { 
				webWindow.dismiss();
				webWindow=null;
			 }
		 }
  }));
}
 var phat=android.os.Environment.getExternalStorageDirectory().getAbsolutePath()+"/games/com.mojang/";
if(!java.io.File(phat).exists())
{
	try
   {
		java.io.File(phat).mkdirs();
		ModPE.downloadFile("xButton.png","https://dl.dropboxusercontent.com/s/i4nl4bcwxq5wgi3/xButton.png?dl=0");
		}
	catch(err)
   {
		print(err);
		}
}
 
 function compareDistance(ent, distance) {
    return Math.abs(Entity.getX(ent) - Player.getX()) < distance && Math.abs(Entity.getY(ent) - Player.getY()) < distance && Math.abs(Entity.getZ(ent) - Player.getZ()) < distance
}


var debugMode=false;
var tickswi=27;
var etickswi=27;
var ticke=0;
function modTick(){
if(b == false){
	ModPE.showTipMessage(ChatColor.RED+"You dont have the license \nto play this Guardian Mod..\n/download to get the license")
	}
	if(b == true) {
if(Guardian1s == true){
	if(debugMode==false){
	if(Level.getGameMode() == 0){
					  if(compareDistance(Guardian1, 10)) {
	var shotYaw1 = Math.atan2((Entity.getZ(Guardian1) - Entity.getZ(getPlayerEnt())), (Entity.getX(Guardian1) - Entity.getX(getPlayerEnt())));
	var shotPitch1 = Math.atan2((Entity.getY(Guardian1) - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(Entity.getX(Guardian1) - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(Entity.getZ(Guardian1) - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot1 = lookDir(((shotYaw1 * 180) / Math.PI) - 90, (shotPitch1 * 180) / Math.PI);
	var xSpawn = Entity.getX(Guardian1) + (-turretShot1.x * 1.5);
	var ySpawn = Entity.getY(Guardian1) + 1 + (turretShot1.y);
	var zSpawn = Entity.getZ(Guardian1) + (-turretShot1.z * 1.5);
	var shotYaw2 = Math.atan2((zSpawn - Entity.getZ(getPlayerEnt())), (xSpawn - Entity.getX(getPlayerEnt())));
	var shotPitch2 = Math.atan2((ySpawn - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(xSpawn - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(zSpawn - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot2 = lookDir(((shotYaw2 * 180) / Math.PI) - 90, (shotPitch2 * 180) / Math.PI);
	var shotArrow = Level.spawnMob(xSpawn, ySpawn, zSpawn, 81); 
	Level.addParticle(8, -turretShot1.x * 3,turretShot1.y * 3,-turretShot1.z * 3, 0, 0, 0, 1);
	Entity.setVelX(shotArrow, -turretShot2.x * 3);
	Entity.setVelY(shotArrow, turretShot2.y * 3);
	Entity.setVelZ(shotArrow, -turretShot2.z * 3);
	Level.playSoundEnt(Guardian1, "random.bow", 1000, 30);
	Entity.addEffect(getPlayerEnt(), 19, 10*10, 3, false, true);
	Entity.addEffect(getPlayerEnt(), 20, 20*10, 3, false, true);
}
}
}
		if(debugMode==true){
					  if(compareDistance(Guardian1, 10)) {
	var shotYaw1 = Math.atan2((Entity.getZ(Guardian1) - Entity.getZ(getPlayerEnt())), (Entity.getX(Guardian1) - Entity.getX(getPlayerEnt())));
	var shotPitch1 = Math.atan2((Entity.getY(Guardian1) - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(Entity.getX(Guardian1) - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(Entity.getZ(Guardian1) - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot1 = lookDir(((shotYaw1 * 180) / Math.PI) - 90, (shotPitch1 * 180) / Math.PI);
	var xSpawn = Entity.getX(Guardian1) + (-turretShot1.x * 1.5);
	var ySpawn = Entity.getY(Guardian1) + 1 + (turretShot1.y);
	var zSpawn = Entity.getZ(Guardian1) + (-turretShot1.z * 1.5);
	var shotYaw2 = Math.atan2((zSpawn - Entity.getZ(getPlayerEnt())), (xSpawn - Entity.getX(getPlayerEnt())));
	var shotPitch2 = Math.atan2((ySpawn - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(xSpawn - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(zSpawn - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot2 = lookDir(((shotYaw2 * 180) / Math.PI) - 90, (shotPitch2 * 180) / Math.PI);
	var shotArrow = Level.spawnMob(xSpawn, ySpawn, zSpawn, 81); 
	Entity.setVelX(shotArrow, -turretShot2.x * 3);
	Entity.setVelY(shotArrow, turretShot2.y * 3);
	Entity.setVelZ(shotArrow, -turretShot2.z * 3);
	Level.playSoundEnt(Guardian1, "random.bow", 1000, 30);
	Entity.addEffect(getPlayerEnt(), 19, 10*10, 3, false, true);
	Entity.addEffect(getPlayerEnt(), 20, 20*10, 3, false, true);
    snowball.push(shotArrow)
}
}

if(hurt1 == true){
 tick1++;
 Entity.setRenderType(Guardian1, HurtedGuardianRenderType.renderType);
if(tick1==40){
  tick1=0;
  hurt1 = false;
  stay1++;
  Entity.setRenderType(Guardian1, GuardianRenderType.renderType);
  }
}
if(hurt1==false){
tickswi--;
if(tickswi==24){
Entity.setRenderType(Guardian1, GuardianSwipeLRenderType.renderType);
if(getTile(Entity.getX(Guardian1),Entity.getY(Guardian1),Entity.getZ(Guardian1)) == 0){
Entity.setVelY(Guardian1,-0.1);
}
if(getTile(Entity.getX(Guardian1),Entity.getY(Guardian1)-3,Entity.getZ(Guardian1)) == 0 || getTile(Entity.getX(Guardian1),Entity.getY(Guardian1)-2,Entity.getZ(Guardian1)) == 0){
	Entity.setVelY(Guardian1,-500);
}
}
if(tickswi==21){
Entity.setRenderType(Guardian1, GuardianSwipeRLRenderType.renderType);
}
if(tickswi==18){
if(getTile(Entity.getX(Guardian1),Entity.getY(Guardian1),Entity.getZ(Guardian1)) == 0){
Entity.setVelY(Guardian1,0.500);
}
}
if(tickswi==15){
Entity.setRenderType(Guardian1, GuardianRenderType.renderType);

}
if(tickswi==12){
Entity.setRenderType(Guardian1, GuardianSwipeRRenderType.renderType);
if(getTile(Entity.getX(Guardian1),Entity.getY(Guardian1),Entity.getZ(Guardian1)) == 0){
Entity.setVelY(Guardian1,-0.1);
var shotYaw1 = Math.atan2((Entity.getZ(getPlayerEnt()) - Entity.getZ(Guardian1)), (Entity.getX(getPlayerEnt()) - Entity.getX(Guardian1)));
	var shotPitch1 = Math.atan2((Entity.getY(getPlayerEnt()) - Entity.getY(Guardian1)), Math.sqrt( (Math.pow(Entity.getX(getPlayerEnt()) - Entity.getX(Guardian1), 2)) + (Math.pow(Entity.getZ(getPlayerEnt()) - Entity.getZ(Guardian1), 2))));
	var turretShot1 = lookDir(((shotYaw1 * 180) / Math.PI) - 90, (shotPitch1 * 180) / Math.PI);
	var xSpawn = Entity.getX(Guardian1) + (-turretShot1.x * 1.5);
	var ySpawn = Entity.getY(Guardian1) + 1 + (turretShot1.y);
	var zSpawn = Entity.getZ(Guardian1) + (-turretShot1.z * 1.5);
	var shotYaw2 = Math.atan2((zSpawn - Entity.getZ(getPlayerEnt())), (xSpawn - Entity.getX(getPlayerEnt())));
	var shotPitch2 = Math.atan2((ySpawn - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(xSpawn - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(zSpawn - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot2 = lookDir(((shotYaw2 * 180) / Math.PI) - 90, (shotPitch2 * 180) / Math.PI);
Entity.setVelX(Guardian1, shotYaw2)
    Entity.setVelZ(Guardian1, shotYaw2)
}
if(getTile(Entity.getX(Guardian1),Entity.getY(Guardian1)-3,Entity.getZ(Guardian1)) == 0 || getTile(Entity.getX(Guardian1),Entity.getY(Guardian1)-2,Entity.getZ(Guardian1)) == 0){
	Entity.setVelY(Guardian1,-500);
}
}

if(tickswi==9){
Entity.setRenderType(Guardian1, GuardianSwipeRRRenderType.renderType);
}
if(tickswi==6){
Entity.setRenderType(Guardian1, GuardianSwipeRRenderType.renderType);
if(getTile(Entity.getX(Guardian1),Entity.getY(Guardian1),Entity.getZ(Guardian1)) == 0){
Entity.setVelY(Guardian1,0.500);

}
}

if(tickswi==3){
Entity.setRenderType(Guardian1, GuardianRenderType.renderType);

tickswi=27;
}
}
else{
}
}
if(ElderGuardian1s == true){
	if(debugMode==false){
	if(Level.getGameMode() == 0){
		
				  if(compareDistance(ElderGuardian1, 10)) {
	var shotYaw1 = Math.atan2((Entity.getZ(ElderGuardian1) - Entity.getZ(getPlayerEnt())), (Entity.getX(ElderGuardian1) - Entity.getX(getPlayerEnt())));
	var shotPitch1 = Math.atan2((Entity.getY(ElderGuardian1) - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(Entity.getX(ElderGuardian1) - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(Entity.getZ(ElderGuardian1) - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot1 = lookDir(((shotYaw1 * 180) / Math.PI) - 90, (shotPitch1 * 180) / Math.PI);
	var xSpawn = Entity.getX(ElderGuardian1) + (-turretShot1.x * 1.5);
	var ySpawn = Entity.getY(ElderGuardian1) + 1 + (turretShot1.y);
	var zSpawn = Entity.getZ(ElderGuardian1) + (-turretShot1.z * 1.5);
	var shotYaw2 = Math.atan2((zSpawn - Entity.getZ(getPlayerEnt())), (xSpawn - Entity.getX(getPlayerEnt())));
	var shotPitch2 = Math.atan2((ySpawn - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(xSpawn - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(zSpawn - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot2 = lookDir(((shotYaw2 * 180) / Math.PI) - 90, (shotPitch2 * 180) / Math.PI);
	var eshotArrow = Level.spawnMob(xSpawn, ySpawn, zSpawn, 81); 
	Level.addParticle(8, -turretShot2.x ,turretShot2.y ,-turretShot2.z , 0, 0, 0, 1);
	Entity.setVelX(eshotArrow, -turretShot2.x * 3);
	Entity.setVelY(eshotArrow, turretShot2.y * 3);
	Entity.setVelZ(eshotArrow, -turretShot2.z * 3);
	Level.playSoundEnt(ElderGuardian1, "random.bow", 1000, 30);
	Entity.addEffect(getPlayerEnt(), 4, 150*20, 3, false, true);
	Entity.addEffect(getPlayerEnt(), 20, 20*10, 3, false, true);
	ModPE.showTipMessage(ChatColor.RED + "Curse....")
	esnowball.push(eshotArrow)
	}
}
}
if(debugMode==true){
		
				  if(compareDistance(ElderGuardian1, 10)) {
	var shotYaw1 = Math.atan2((Entity.getZ(ElderGuardian1) - Entity.getZ(getPlayerEnt())), (Entity.getX(ElderGuardian1) - Entity.getX(getPlayerEnt())));
	var shotPitch1 = Math.atan2((Entity.getY(ElderGuardian1) - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(Entity.getX(ElderGuardian1) - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(Entity.getZ(ElderGuardian1) - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot1 = lookDir(((shotYaw1 * 180) / Math.PI) - 90, (shotPitch1 * 180) / Math.PI);
	var xSpawn = Entity.getX(ElderGuardian1) + (-turretShot1.x * 1.5);
	var ySpawn = Entity.getY(ElderGuardian1) + 1 + (turretShot1.y);
	var zSpawn = Entity.getZ(ElderGuardian1) + (-turretShot1.z * 1.5);
	var shotYaw2 = Math.atan2((zSpawn - Entity.getZ(getPlayerEnt())), (xSpawn - Entity.getX(getPlayerEnt())));
	var shotPitch2 = Math.atan2((ySpawn - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(xSpawn - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(zSpawn - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot2 = lookDir(((shotYaw2 * 180) / Math.PI) - 90, (shotPitch2 * 180) / Math.PI);
	var eshotArrow = Level.spawnMob(xSpawn, ySpawn, zSpawn, 81); 
	Level.addParticle(8, -turretShot2.x ,turretShot2.y ,-turretShot2.z , 0, 0, 0, 1);
	Entity.setVelX(eshotArrow, -turretShot2.x * 3);
	Entity.setVelY(eshotArrow, turretShot2.y * 3);
	Entity.setVelZ(eshotArrow, -turretShot2.z * 3);
	Level.playSoundEnt(ElderGuardian1, "random.bow", 1000, 30);
	Entity.addEffect(getPlayerEnt(), 4, 150*20, 3, false, true);
	Entity.addEffect(getPlayerEnt(), 20, 20*10, 3, false, true);
	ModPE.showTipMessage(ChatColor.RED + "Curse....")
	}
	}
if(ehurt1 == true){
 etick1++;
 Entity.setRenderType(ElderGuardian1, HurtedElderGuardianRenderType.renderType);
if(etick1==40){
  etick1=0;
  ehurt1 = false;
  estay1++;
  Entity.setRenderType(ElderGuardian1, ElderGuardianRenderType.renderType);
  }
}
if(ehurt1==false){
etickswi--;
if(etickswi==24){
Entity.setRenderType(ElderGuardian1, ElderGuardianSwipeLRenderType.renderType);
if(getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1),Entity.getZ(ElderGuardian1)) == 0){
Entity.setVelY(ElderGuardian1,0.500);
}
}
if(etickswi==21){
Entity.setRenderType(ElderGuardian1, ElderGuardianSwipeRLRenderType.renderType);

}
if(etickswi==18){
Entity.setRenderType(ElderGuardian1, ElderGuardianSwipeLRenderType.renderType);
if(getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1),Entity.getZ(ElderGuardian1)) == 0){
Entity.setVelY(ElderGuardian1,-0.1);
var shotYaw1 = Math.atan2((Entity.getZ(getPlayerEnt()) - Entity.getZ(ElderGuardian1)), (Entity.getX(getPlayerEnt()) - Entity.getX(ElderGuardian1)));
	var shotPitch1 = Math.atan2((Entity.getY(ElderGuardian1) - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(Entity.getX(ElderGuardian1) - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(Entity.getZ(ElderGuardian1) - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot1 = lookDir(((shotYaw1 * 180) / Math.PI) - 90, (shotPitch1 * 180) / Math.PI);
	var xSpawn = Entity.getX(ElderGuardian1) + (-turretShot1.x * 1.5);
	var ySpawn = Entity.getY(ElderGuardian1) + 1 + (turretShot1.y);
	var zSpawn = Entity.getZ(ElderGuardian1) + (-turretShot1.z * 1.5);
	var shotYaw2 = Math.atan2((zSpawn - Entity.getZ(getPlayerEnt())), (xSpawn - Entity.getX(getPlayerEnt())));
	var shotPitch2 = Math.atan2((ySpawn - Entity.getY(getPlayerEnt())), Math.sqrt( (Math.pow(xSpawn - Entity.getX(getPlayerEnt()), 2)) + (Math.pow(zSpawn - Entity.getZ(getPlayerEnt()), 2))));
	var turretShot2 = lookDir(((shotYaw2 * 180) / Math.PI) - 90, (shotPitch2 * 180) / Math.PI);
Entity.setVelX(ElderGuardian1, shotYaw2)
    Entity.setVelZ(ElderGuardian1, shotYaw2)
}
if(getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1)-3,Entity.getZ(ElderGuardian1)) == 0 || getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1)-2,Entity.getZ(ElderGuardian1)) == 0){
	Entity.setVelY(ElderGuardian1,-500);
}
}
if(etickswi==15){
Entity.setRenderType(ElderGuardian1, ElderGuardianRenderType.renderType);
}
if(etickswi==12){
Entity.setRenderType(ElderGuardian1, ElderGuardianSwipeRRenderType.renderType);
if(getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1),Entity.getZ(ElderGuardian1)) == 0){
Entity.setVelY(ElderGuardian1,0.500);
}
}
if(etickswi==9){
Entity.setRenderType(ElderGuardian1, ElderGuardianSwipeRRRenderType.renderType);
}
if(etickswi==6){
Entity.setRenderType(ElderGuardian1, ElderGuardianSwipeRRenderType.renderType);
if(getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1),Entity.getZ(ElderGuardian1)) == 0){
Entity.setVelY(ElderGuardian1,-0.1);
}
if(getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1)-3,Entity.getZ(ElderGuardian1)) == 0 || getTile(Entity.getX(ElderGuardian1),Entity.getY(ElderGuardian1)-2,Entity.getZ(ElderGuardian1)) == 0){
	Entity.setVelY(ElderGuardian1,-500);
}
}
if(etickswi==3){
Entity.setRenderType(ElderGuardian1, ElderGuardianRenderType.renderType);
etickswi=27;
}
}
else{
}
}
}
					
}
function attackHook(a,v){
if(b==true){
if(v == Guardian1){
hurt1 = true;
preventDefault();
Entity.setHealth(Guardian1,Entity.getHealth(Guardian1) - 2);
Entity.setFireTicks(Guardian1,1);
}
if(v == ElderGuardian1){
ehurt1 = true;
preventDefault();
Entity.setHealth(ElderGuardian1,Entity.getHealth(ElderGuardian1) - 2);
Entity.setFireTicks(ElderGuardian1,1);
}
}
}
function vector3d(x, y, z) {
    this.x = x;
    this.y = y;
    this.z = z;
}

function lookDir(yaw, pitch) {
    var direction = new vector3d(0, 0, 0);
    direction.y = -Math.sin(java.lang.Math.toRadians(pitch));
    direction.x = -Math.sin(java.lang.Math.toRadians(yaw)) * Math.cos(java.lang.Math.toRadians(pitch));
    direction.z = Math.cos(java.lang.Math.toRadians(yaw)) * Math.cos(java.lang.Math.toRadians(pitch));
    return direction;
}

var stay = 0;
var estay = 0;
